#! /bin/sh
#
### BEGIN INIT INFO
# Provides:          sleepd
# Required-Start:    $syslog $local_fs $remote_fs
# Required-Stop:     $syslog $local_fs $remote_fs
# Should-Start:      dbus hal
# Should-Stop:       dbus hal
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Sleep daemon
# Description:       init script for the sleepd daemon
### END INIT INFO

DAEMON=/usr/sbin/sleepd
NAME=sleepd

test -f $DAEMON || exit 0

. /lib/lsb/init-functions

set -e

# Source defaults file; edit that file to configure this script.
PARAMS=""
if [ -e /etc/default/sleepd ]; then
	. /etc/default/sleepd
fi

case "$1" in
	start)
		# Ensure apm module is loaded.
		test -e /dev/apm_bios && touch /dev/apm_bios

		log_daemon_msg "Starting sleep daemon" "sleepd"
		eval start_daemon -p /var/run/$NAME.pid $DAEMON $PARAMS
		log_end_msg $?
	;;
	stop)
		log_daemon_msg "Stopping sleep daemon" "sleepd"
		killproc -p /var/run/$NAME.pid $DAEMON TERM
		log_end_msg $?
	;;
	status)
		status_of_proc $DAEMON sleepd
		log_end_msg $?
	;;
	restart|force-reload)
		$0 stop
		sleep 1
		$0 start
	;;
	*)
		echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
		exit 1
		;;
esac

exit 0
